# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
ja:
  languageCode: ja
  contentDir: content/ja

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  contentDir: content/en
  title: Hongo Particle Physics Group
  contentDir: content/en
  params:
    description: Particle Physics Group at Hongo Campus, the University of Tokyo
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
